<?php
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \WolfSellers\Subscriptions\Block\Onepage\Success */ ?>
<?php
/** @var \WolfSellers\Attachments\Helper\Attach $helperAttach */
$helperAttach = $this->helper('WolfSellers\Attachments\Helper\Attach');
$block->getProductLens();
$suscripcion = $block->getSubscriptionConsecutive();
$email = $block->getEmail();
?>
<div class="checkout-success">
    <?php if ($block->getSubscriptionsId() && ($block->leftEye() OR $block->rightEye())): ?>
        <p class="email">
            <?= __('La suscripcion ') ?>
            <?php echo $suscripcion ?>
            <?= __('ha sido creada exitosamente, está a punto de concluirse y contar para tu meta CLS.') ?>
            <br><br>
            <?= __('Solo falta un paso más, garantizar que el paciente registre su método de pago, verifica que haya recibido el correo a su dirección registrada: ') ?>
            <?php echo $email ?>
            <br><br>
            <?= __('¡Contamos con tu apoyo!') ?>
        </p>
        <?php echo $block->getAdditionalInfoHtml() ?>
    <?php echo $this->getLayout()
          ->createBlock('Magento\Cms\Block\Block')
          ->setBlockId('social-networks')
          ->toHtml(); ?>


    <div class="eyes">
        <div class="head-line"></div>
        <div class="eyes-container">
            <?php if ($block->leftEye()) : ?>
            <div id="ojo_izq" class="ojo_izquierdo">
                <p class="eye"><?=__('Left Eye')?></p>    
                <div class="marca"><?= $block->leftEye()->getAttributeText('marca') ?></div>
                <p class="title"> <?= $block->leftEye()->getName() ?></p>
                <?php if($block->leftEye()->getAttributeText('indicado_para')): ?>
                <p><span><?=__('Indicated for: ')?> </span><strong><?= $block->leftEye()->getAttributeText('indicado_para') ?></strong></p>
                <?php endif; ?>
                <?php if($block->getPeriodicity()!==false):?>
                <p><span><?=__('Subscription Every: ')?> </span><strong><?= $block->getPeriodicity().' meses' ?></strong></p>
                <?php endif; ?>
                <div class="ojo-parameters">
                <ul>
                    <li>
                        <span><?=__('Pder.(SPH): ')?>  </span>
                        <?= $block->leftEye()->getAttributeText('esfera') ?>
                    </li>
                    <li>
                        <span><?=__('Base Curve: ')?></span>
                        <?= $block->leftEye()->getAttributeText('curvabase') ?>
                    </li>
                    <li>
                        <span><?=__('Diameter: ')?></span>
                        <?= $block->leftEye()->getAttributeText('diametro') ?>
                    </li>
                    <?php if($helperAttach->getIndicadoForm($block->leftEye()->getAttributeText('indicado_para')) == "astigmatismo"): ?>
                    <li>
                        <span><?=__('Cylinder: ')?></span>
                        <?= $block->leftEye()->getAttributeText('cilindro') ?></li>
                    <li>
                        <span><?=__('Eje: ')?></span>
                        <?=  $block->leftEye()->getAttributeText('eje') ?>
                    </li>
                    <?php endif; ?>
                </ul>
                </div>

            </div>
            <?php endif; ?>
            <div class="eyes-line"></div>

            <?php if ($block->rightEye()) : ?>
            <div id="ojo_der" class="ojo_derecho">
                <p class="eye"><?=__('Right Eye')?></p>
                <div class="marca"><?= $block->rightEye()->getAttributeText('marca') ?></div>
                <p class="title"><?= $block->rightEye()->getName() ?></p>
                <?php if($block->rightEye()->getAttributeText('indicado_para')): ?>
                <p><span><?=__('Indicated for: ')?> </span><strong><?= $block->rightEye()->getAttributeText('indicado_para') ?></strong></p>
                <?php endif; ?>
                <?php if($block->getPeriodicity()!==false):?>
                <p><span><?=__('Subscription Every: ')?> </span><strong><?= $block->getPeriodicity().' meses' ?></strong></p>
                <?php endif; ?>
                <div class="ojo-parameters">
                    <ul>
                        <li>
                            <span><?=__('Pder.(SPH): ')?>  </span>
                            <?= $block->rightEye()->getAttributeText('esfera') ?>
                        </li>
                        <li>
                            <span><?=__('Base Curve: ')?></span>
                            <?= $block->rightEye()->getAttributeText('curvabase') ?>
                        </li>
                        <li>
                            <span><?=__('Diameter: ')?></span>
                            <?= $block->rightEye()->getAttributeText('diametro') ?>
                        </li>
                        <?php if($helperAttach->getIndicadoForm($block->rightEye()->getAttributeText('indicado_para')) == "astigmatismo"): ?>
                        <li>
                            <span><?=__('Cylinder: ')?></span>
                            <?= $block->rightEye()->getAttributeText('cilindro') ?>
                        </li>
                        <li>
                            <span><?=__('Eje: ')?></span>
                            <?= $block->rightEye()->getAttributeText('eje') ?>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>

    <?php endif; ?>
    <!--div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div-->
</div>
