<?php

/** @var $block WolfSellers\PaymentLink\Block\Form\Openpay */

?>

<div class="form-change-container" style="padding-top: 50px;">
    <div class="openpay-form">
        <div class="bkng-tb-cntnt">
            <div class="pymnts">
                <div class="type-of-target" style="width: 100%; margin: auto;">
                    <div class="header" style="width: 100%; margin: auto; text-align: center;">
                        <h3><?=__('El link de pago ya expiró o el cargo ya fue realizado.')?></h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
